#import "../../../../components/Calendar.gql"
query getEventWithSchedule($data: ClearEventWhereUniqueInput!) {
    clear {
        event(where: $data) {
            id
            name
            ...EventCalendarFragment
        }
    }
}
