#import "../../../../components/forms/Notes.gql"
#import "../../../../components/forms/ScheduleItem.gql"

query GetScheduleItemQuery($data: ClearScheduleItemWhereUniqueInput!) {
    clear {
        scheduleItem(where: $data) {
            ...ScheduleItemFormFragment
            ...ScheduleItemNotesFragment
            displayTimeWithDate
            event {
                id
                name
            }
        }
    }
}
