#import "../../../components/EventRestriction.gql"
#import "../../../components/LinkEventRestrictionsModal.gql"

query GetEventRestrictionsQuery($data: ClearEventWhereUniqueInput!) {
    clear {
        event(where: $data) {
            id
            name
            cmsEventRestrictions {
                id
                name
                details
                icon {
                    url
                }
            }
            region {
                localizationConfig {
                    requiredEventRestrictions {
                        items {
                            id
                            name
                        }
                    }
                }
            }
        }
    }

    cms {
        eventRestrictions {
            items {
                ...LinkEventRestrictionsModalFragment
            }
        }
    }
}
