#import "../../../components/EventRestriction.gql"
#import "../../../components/LinkEventRestrictionsModal.gql"

query GetEventRestrictionsQuery($data: ClearEventWhereUniqueInput!) {
    clear {
        event(where: $data) {
            id
            name
            eventRestrictions {
                ...EventRestrictionFragment
            }
        }
        eventRestrictions {
            ...LinkEventRestrictionsModalFragment
        }
    }
}
