#import "../../../components/VenueInfo.gql"
#import "../../../components/RegistrationsToggleWithChecklist.gql"
#import "../../../components/SponsorOverview.gql"
#import "../../../components/RegistrationGraph.gql"
#import "../../../components/ScheduleBox.gql"
#import "../../../components/forms/Notes.gql"
#import "../../../components/forms/Event.gql"
#import "../../../components/forms/Venue.gql"
#import "../../../components/TicketBox.gql"
#import "../../../components/DaysUntilEvent.gql"
#import "../../../components/EventRestrictionBox.gql"

query getEventQuery($data: ClearEventWhereUniqueInput!) {
    clear {
        event(where: $data) {
            id
            name
            displayDate
            eventGroup {
                name
            }
            venue {
                ...VenueInfoFragment
                ...VenueFormFragment
            }
            eventRestrictions {
                ...EventRestrictionBoxFragment
            }
            ...RegistrationsToggleWithChecklistFragment
            ...SponsorOverviewFragment
            ...RegistrationGraphFragment
            ...ScheduleBoxFragment
            ...EventNotesFragment
            ...EventFormFragment
            ...TicketBoxFragment
            ...DaysUntilEventFragment
        }
    }
}
