mutation SendNotification ($eventId: String!, $guardian: Boolean!, $emailBody: String, $emailSubject: String, $smsBody: String) {
  clear {
    sendNotification(
      eventWhere:{id:$eventId},
      emailBody: $emailBody,
      emailSubject: $emailSubject,
      smsBody: $smsBody,
      guardian: $guardian
    )
  }
}
query getEventQuery($data: ClearEventWhereUniqueInput!) {
    clear {
        event(where: $data) {
            id
            name
        }
    }
}
