query getEventPreRegistrationsQuery($data: ClearEventWhereUniqueInput!) {
    clear {
        event(where: $data) {
            id
            name
            interestedEmails {
                id
                email
            }
        }
    }
}
