#import "../../../components/SponsorBox.gql"

query SponsorsGetEventQuery($data: ClearEventWhereUniqueInput!) {
    clear {
        event(where: $data) {
            id
            name
            region {
              currencySymbol
            }
            sponsors {
                id
                ...SponsorBoxFragment
            }
        }
    }
}
