query getEvent($data: ClearEventWhereUniqueInput!) {
    clear {
        event(where: $data) {
            id
            name
        }
    }
}

mutation createTicket($data: ClearTicketCreateInput!) {
    clear {
        createTicket(data: $data) {
            id
        }
    }
}
