#import "../../../../components/Ticket.gql"
query getEventWithTickets($data: ClearEventWhereUniqueInput!) {
    clear {
        event(where: $data) {
            id
            name
            tickets {
                ...Ticket
                createdAt
                firstName
                lastName
                age
                email
                phone
                type
                guardian {
                    firstName
                    lastName
                    email
                    phone
                }
            }
        }
    }
}

mutation createTicket($data: ClearTicketCreateInput!, ) {
    clear {
        createTicket(data: $data) {
            id
        }
    }
}

# this is a separate query because it generates it live which takes resources
query getWaiverBook($data: ClearEventWhereUniqueInput!) {
    clear {
        event(where: $data) {
            waiverBook
        }
    }
}
