#import "../../../../components/Ticket.gql"
query getEvent($data: ClearEventWhereUniqueInput!) {
    clear {
        event(where: $data) {
            id
            name
        }
    }
}

query getTickets($data: ClearEventWhereUniqueInput!) {
    clear {
        event(where: $data) {
            tickets(orderBy:[{lastName:asc}]) {
                ...Ticket
                id
                createdAt
                firstName
                lastName
                age
                email
                phone
                type
                checkedIn
                checkedOut
                guardian {
                    firstName
                    lastName
                    email
                    phone
                }
                organization: getMetadata(key: "organization")
                surveyResponses
            }
        }
    }
}

mutation createTicket($data: ClearTicketCreateInput!, ) {
    clear {
        createTicket(data: $data) {
            id
        }
    }
}

# this is a separate query because it generates it live which takes resources
query getWaiverBook($data: ClearEventWhereUniqueInput!) {
    clear {
        event(where: $data) {
            waiverBook
        }
    }
}
