#import "../../../components/EmailTemplate.gql"
#import "../../../components/forms/EmailTemplate.gql"
query getEmailTemplatesQuery {
    clear {
        emailTemplates {
            ...EmailTemplateFragment
            ...EmailTemplateFormFragment
        }
    }
}
