#import "../../../../../components/Ticket.gql"
#import "../../../../../components/forms/Ticket.gql"
#import "../../../../../components/forms/Guardian.gql"
#import "../../../../../components/forms/Notes.gql"
query getTicket($data: ClearTicketWhereUniqueInput!) {
    clear {
        ticket(where: $data) {
            id
            metadata
            createdAt
            waiverPdfUrl
            payment {
                stripePaymentIntentId
            }
            event {
                id
                name
                displayDate
            }
            promoCode {
                code
            }
            ...Ticket
            ...TicketFormFragment
            ...TicketNotesFragment
            guardian {
                ...GuardianFormFragment
                firstName
                lastName
                email
                phone
                whatsApp
            }
        }
    }
}
