fragment ScheduleItemFragment on ClearScheduleItem {
    id
    name
    internal
    finalized
    type
    start
    end
    description
    displayTime
    hostName
    hostEmail
    hostPronoun
}
fragment EventCalendarFragment on ClearEvent {
    id
    name
    startDate
    endDate
    schedule {
        ...ScheduleItemFragment
    }
    eventGroup {
        schedule {
            ...ScheduleItemFragment
        }
    }
}
