fragment LinkEventRestrictionsModalFragment on CmsEventRestriction {
        id
        name
}

mutation UpdateEventRestrictionsMutation($where: ClearEventWhereUniqueInput! $restrictions: ClearEventUpdatecontentfulEventRestrictionsInput! ) {
        clear {
                updateEvent(where: $where, data: {contentfulEventRestrictions: $restrictions}) {
                        id
                }
        }
}
