fragment RegistrationsToggleWithChecklistFragment on ClearEvent {
    id
    registrationsOpen
    venue {
        capacity
        contactName
        contactEmail
        contactPhone
        address
        mapLink
    }
    eventRestrictions {
        id
    }
    schedule {
        finalized
    }
    sponsors {
        id
    }
    promoCodes {
        id
    }
    allRegistrations: tickets {
        id
    }
    studentRegistrations: tickets(where: { type: {equals: STUDENT} }) {
        id
    }
    region {
        countryName
    }
}

mutation RegistrationsToggleMutation($eventWhere: ClearEventWhereUniqueInput!, $data: Boolean!) {
    clear {
        updateEvent(where: $eventWhere, data: {registrationsOpen: {set: $data}}) {
            id
        }
    }
}
