fragment TicketBoxFragment on ClearEvent {
    ticketPrice
    registrationCutoff
    earlyBirdCutoff
    earlyBirdPrice
    canEarlyBirdRegister
    canRegister
    region {
        currencySymbol
    }
}
