fragment Ticket on ClearTicket {
    id
    firstName
    lastName
    age
    email
    phone
    whatsApp
    type
    needsGuardian
    waiverSigned
    waiverUrl
    checkedIn
    checkedOut
    vaccineVerified: getMetadata(key: "vaccineVerified")
    surveyResponses
    promoCode {
      code
    }
    event {
      id
      overnightMinAge
    }
}

mutation checkin($where: ClearTicketWhereUniqueInput!) {
  clear {
    checkinout: checkin(where: $where) { checkedIn checkedOut }
  }
}

mutation checkout($where: ClearTicketWhereUniqueInput!) {
  clear {
    checkinout: checkout(where: $where) { checkedIn checkedOut }
  }
}

mutation sendWaiverReminder($where: ClearTicketWhereUniqueInput!, $regenerate: Boolean) {
  clear {
    sendWaiverReminder(where: $where, regenerate: $regenerate)
  }
}

