#import "./forms/Venue.gql"

fragment VenueInfoFragment on ClearVenue {
    id
    name
    address
    mapLink
    capacity
    contactEmail
    contactName
    contactPhone
    notes: getMetadata(key: "notes")
    ...VenueFormFragment
}
