#import "../../components/Event.gql"

query getEvents($where: ClearEventWhereInput) {
    clear {
        eventGroups(orderBy:[{startDate:desc}]) {
            name
            events (orderBy: [{startDate:asc}], where: $where) {
                endDate
                ...EventFragment
            }
        }
    }
}
