#import "../../components/Event.gql"

query getEvents($where: [ClearEventWhereInput!]) {
    clear {
        eventGroups(orderBy:[{startDate:desc}]) {
            id
            name
            events (orderBy: [{startDate:asc}], where: { AND: $where }) {
                endDate
                ...EventFragment
            }
            otherEvents: events(where: { NOT: $where }) {
                id
                name
            }
        }
    }
}
