mutation CreateEmailTemplateMutation($data: ClearEmailTemplateCreateInput!) {
    clear {
        createEmailTemplate(data: $data) {
            id
        }
    }
}

mutation UpdateEmailTemplateMutation($where: ClearEmailTemplateWhereUniqueInput!, $data: ClearEmailTemplateUpdateInput!) {
    clear {
        updateEmailTemplate(where: $where, data: $data) {
            id
        }
    }
}

mutation DeleteEmailTemplateMutation($where: ClearEmailTemplateWhereUniqueInput!) {
    clear {
        deleteEmailTemplate(where: $where) {
            id
        }
    }
}

fragment EmailTemplateFormFragment on ClearEmailTemplate {
    id
    name
    automatic
    fromName
    fromEmail
    replyTo
    subject
    template
    sendText
    textMsg
    sendTo
    when
    whenFrom
    sendLate
    sendInWorkHours
    sendAfterEvent
    sendParent
    marketing
    extraFilters
}
