mutation CreateEventRestrictionMutation($data: ClearEventRestrictionCreateInput!) {
    clear {
        createEventRestriction(data: $data) {
            id
        }
    }
}

mutation UpdateEventRestrictionMutation($where: ClearEventRestrictionWhereUniqueInput!, $data: ClearEventRestrictionUpdateInput!) {
    clear {
        updateEventRestriction(where: $where, data: $data) {
            id
        }
    }
}

mutation DeleteEventRestrictionMutation($where: ClearEventRestrictionWhereUniqueInput!) {
    clear {
        deleteEventRestriction(where: $where) {
            id
        }
    }
}

fragment EventRestrictionFormFragment on ClearEventRestriction {
    id
    name
    title
    details
}

mutation UploadEventRestrictionIconMutation($where: ClearEventRestrictionWhereUniqueInput! $file: Upload!) {
    clear {
        uploadEventRestrictionIcon(where: $where, upload: $file) {
            iconUri
        }
    }
}
