fragment GuardianFormFragment on ClearPerson {
    id
    firstName
    lastName
    email
    phone
    whatsApp
    username
}

mutation AddGuardianMutation($ticketId: String! $data: ClearPersonCreateWithoutTicketInput!) {
    clear {
        updateTicket(where: {id: $ticketId} data: {guardian: {create: $data }}) {
            id
        }
    }
}

mutation UpdateGuardianMutation($where: ClearPersonWhereUniqueInput!, $data: ClearPersonUpdateInput!) {
    clear {
        updatePerson(where: $where, data: $data) {
            id
        }
    }
}

mutation DeleteGuardianMutation($where: ClearPersonWhereUniqueInput!) {
    clear {
        deletePerson(where: $where) {
            id
        }
    }
}
