fragment PersonFormFragment on ClearPerson {
    id
    firstName
    lastName
    email
    phone
    pronouns
}

mutation CreatePersonMutation($data: ClearPersonCreateInput!) {
    clear {
        createPerson(data: $data) {
            id
        }
    }
}

mutation UpdatePersonMutation($where: ClearPersonWhereUniqueInput!, $data: ClearPersonUpdateInput!) {
    clear {
        updatePerson(where: $where, data: $data) {
            id
        }
    }
}

mutation DeletePersonMutation($where: ClearPersonWhereUniqueInput!) {
    clear {
        deletePerson(where: $where) {
            id
        }
    }
}
