fragment PromoCodeFormFragment on ClearPromoCode {
    type
    code
    amount
    uses
    enablesUber: getMetadata(key: "uber")
    enablesLaptops: getMetadata(key: "laptop")
}

mutation CreatePromoCodeMutation($data: ClearPromoCodeCreateInput!) {
    clear {
        createPromoCode(data: $data) {
            id
        }
    }
}

mutation UpdatePromoCodeMutation($where: ClearPromoCodeWhereUniqueInput!, $data: ClearPromoCodeUpdateInput!) {
    clear {
        updatePromoCode(where: $where, data: $data) {
            id
        }
    }
}

mutation DeletePromoCodeMutation($where: ClearPromoCodeWhereUniqueInput!) {
    clear {
        deletePromoCode(where: $where) {
            id
        }
    }
}

mutation SetPromoCodeMetatataMutation($id: String!, $key: String!, $value: String!) {
  clear {
    setPromoCodeMetadata(where: {id: $id}, key: $key, value: $value) { id }
  }
}
