fragment TicketFormFragment on ClearTicket {
    firstName
    lastName
    email
    phone
    whatsApp
    age
    type
    username
}
mutation CreateTicketMutation($data: ClearTicketCreateInput!) {
    clear {
        createTicket(data: $data) {
            id
        }
    }
}

mutation UpdateTicketMutation($where: ClearTicketWhereUniqueInput!, $data: ClearTicketUpdateInput!) {
    clear {
        updateTicket(where: $where, data: $data) {
            id
        }
    }
}

mutation DeleteTicketMutation($where: ClearTicketWhereUniqueInput!) {
    clear {
        deleteTicket(where: $where) {
            id
        }
    }
}
