fragment VenueFormFragment on ClearVenue {
    name
    capacity
    addressLine1
    addressLine2
    addressLine3
    city
    state
    stateAbbreviation
    zipCode
    country
    countryAbbreviation
    mapLink
    contactName
    contactEmail
    contactPhone
    wifiSsid
    wifiPassword
}
mutation CreateVenueMutation($data: ClearVenueCreateInput!) {
    clear {
        createVenue(data: $data) {
            id
        }
    }
}

mutation UpdateVenueMutation($where: ClearVenueWhereUniqueInput!, $data: ClearVenueUpdateInput!) {
    clear {
        updateVenue(where: $where, data: $data) {
            id
        }
    }
}

mutation DeleteVenueMutation($where: ClearVenueWhereUniqueInput!) {
    clear {
        deleteVenue(where: $where) {
            id
        }
    }
}
